apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubernetes-platform-app.fullname" . }}-secret
  labels:
    {{- include "kubernetes-platform-app.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $val := .Values.secrets }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
