apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubernetes-platform-app-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/PandaVerse09/kubernetes-platform-gitops.git'
    targetRevision: main
    path: charts/application
    helm:
      valueFiles:
        - ../../environments/prod/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
